### ISSUE TITLE
hey dude

### ISSUE THREAD

**Issue by welilili** [echoTheLiar/DoubanAuto#1]
大兄弟，为啥我运行不了？发不了帖，comment倒是可以，remove也可以。所有的我都仔细检查了，没发现哪错了，真正奇怪

**Comment by echoTheLiar** [comment]
你可以：
1. 如果有，贴下报错信息或者日志输出；
2. 在哪个小组发帖，我在我这边复现下；

**Comment by welilili** [comment]
哈哈，自己解决了，豆瓣有反爬虫，爬多了就不给用，隔天就好了。
对啦，给份那个very_active_group.txt文件可以不？感谢！！

**Comment by echoTheLiar** [comment]
欢迎在之前提交的版本中自取~
