### ISSUE TITLE
the value is empty

### ISSUE THREAD

**Issue by zzm88** [echoTheLiar/DoubanAuto#3]
[2018-02-08 08:13:06] [WARNING] the value is empty:
[2018-02-08 08:13:06] [ERROR] join group_id:21106 failed, exceptions info: Invalid URL '': No schema supplied. Perhaps you meant http://?

运行auto join 时显示如上错误

后来查到原因是第二次运行时，很多组我已经加入过了。我建议可以加入一个组就从active group id.txt中删除对应的id
需要PR么

**Comment by echoTheLiar** [comment]
example/autojoin.py第13行
group_id_sets_to_join = group_id_sets - group_joins_sets
这一步通过差集去掉用户已加入的小组，所以问题应该不是出在这里。
考虑是否小组无法加入？（需要申请才能加入）

**Comment by echoTheLiar** [comment]
example/autojoin.py第13行
group_id_sets_to_join = group_id_sets - group_joins_sets
这一步通过差集去掉用户已加入的小组，所以问题应该不是出在这里。
如果发现确为程序bug，欢迎提交修改，一同维护该项目~
感谢反馈~

**Comment by zzm88** [comment]
我知道了，是因为我没有改user_id……
